version: '3.8'

services:

  web-app:
    #    image: vickythawne/springboot-demo:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: web-app
    #    environment:
    #      POSTGRES_DATABASE_HOST: postgres-ecard
    ports:
      - "8080:8080"
    depends_on:
      - redis-cache
      - postgres-db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-db:5432/demo_db
      SPRING_DATASOURCE_USERNAME: demo_user
      SPRING_DATASOURCE_PASSWORD: demo@123

  redis-cache:
    container_name: redis-cache
    image: redis:7.2.4-alpine
#    restart: always
    ports:
      - "6379:6379"
    command: redis-server --loglevel warning
    volumes:
      - redis-cache:/data

  postgres-db:
    container_name: postgres-db
    image: postgres:15.2
    volumes:
      - postgres_db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: demo_db
      POSTGRES_USER: demo_user
      POSTGRES_PASSWORD: demo@123
    ports:
      - "5434:5432"

# Persisted data across application restarts
volumes:
  postgres_db_data: {}
  redis-cache:
    driver: local
