server:
  port: 8080

spring:
  application:
    name: demo
  datasource:
    url: jdbc:postgresql://localhost:5432/ekaantik-gradle-starter
    username: ekaantik-admin
    password: ekaantik@123
    driverClassName: org.postgresql.Driver

  jpa:
    hibernate.ddl-auto: update
    hibernate.default_schema: public
    show-sql: false
    properties.hibernate.format_sql: true
    properties.hibernate.jdbc.time_zone: UTC

upload:
  path: C:/Users/rohit/Desktop/Myfiles/