server:
  port: 8080
  servlet:
    context-path: '/demo'
spring:
  application:
    name: demo
  datasource:
    url: jdbc:postgresql://postgres-db:5434/demo_db
    username: demo_user
    password: demo@123
    driverClassName: org.postgresql.Driver
  data:
    redis:
      database: 0
      host: redis-cache
      port: 6379
      enabled : true
  jpa:
    hibernate.ddl-auto: update
    hibernate.default_schema: public
    show-sql: false
    properties.hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
    properties.hibernate.format_sql: true
    properties.hibernate.jdbc.time_zone: UTC
  servlet:
    multipart:
      max-file-size: 30MB
      max-request-size: 50MB

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

image:
    path: /home/ubuntu/workspace/
    max-file-size: 5242880 # bytes = 5 MB
    file-format: jpg, jpeg , png

video:
    path: /home/ubuntu/workspace/
    max-file-size: 10000000 #bytes = 10MB
    file-format: mp4

token:
  signing:
    key: u5kLX1yVaiArajokYDFkGiFNTGzQbYJt6uQ7QtcI
  expiration:
    time: 60000000