server:
  port: 8080
  servlet:
    context-path: '/demo'
spring:
  application:
    name: demo
  datasource:
    url: jdbc:postgresql://localhost:5434/demo_db
    username: demo_user
    password: demo@123
    driverClassName: org.postgresql.Driver

  jpa:
    hibernate.ddl-auto: create
    hibernate.default_schema: public
    show-sql: false
    properties.hibernate.format_sql: true
    properties.hibernate.jdbc.time_zone: UTC
#  servlet:
#    multipart:
#      img-max-file-size: 1MB
#      max-request-size: 1MB

image:
    path: C:/Users/rohit/Desktop/Myfiles/
    img-max-file-size: 1 #MB
    file-format:
      - jpg
      - jpeg
      - png

video:
    path: C:/Users/rohit/Desktop/Myfiles/
    video-max-file-size: 10 #MB
    file-format:
      - mp4

token:
  signing:
    key: u5kLX1yVaiArajokYDFkGiFNTGzQbYJt6uQ7QtcI
