server:
  port: 8080
  servlet:
    context-path: '/demo'
spring:
  application:
    name: demo
  datasource:
    url: jdbc:postgresql://localhost:5434/demo_db
    username: demo_user
    password: demo@123
    driverClassName: org.postgresql.Driver

  jpa:
    hibernate.ddl-auto: create
    hibernate.default_schema: public
    show-sql: false
    properties.hibernate.format_sql: true
    properties.hibernate.jdbc.time_zone: UTC
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

upload:
  path: C:/Users/rohit/Desktop/Myfiles/
  pathLicense: abc
  pathidentitycard : abc
  pathlogo : abc
  pathcoverimage : abc
  pathicovervideo : abc

token:
  signing:
    key: u5kLX1yVaiArajokYDFkGiFNTGzQbYJt6uQ7QtcI

origin.host.list: http://localhost:80
origin.host.flag: TRUE